[package]
name = "rad_remote"
version = "0.1.0"
edition = "2021"

[dependencies]
rad_compositor = { path = "../rad_compositor" }

actix-web = "4.9.0"
serde = "1.0.*"
toml = "0.8.19"
futures = "0.3.31"
tokio = "1.42.*"
log = "0.4.*"