[package]
name = "rad_compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
coarsetime = "0.1.*"
futures = "0.3.31"
log = "0.4.*"
symphonia = { version = "0.5.*", features = ["mpa"] }
tokio = "1.42.*"
rad_storage = { path = "../rad_storage" }