[package]
name = "rad_compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
# dasp_sample = "0.11.0"
coarsetime = "0.1.34"
log = "0.4.22"
# minimp3 = "0.5.1"
# puremp3 = "0.1.0"
symphonia = { version = "0.5.4", features = ["mpa"] }
